### ISSUE TITLE
检测问题

### ISSUE THREAD

**Issue by zhangleqin** [czj2369/jd_tb_auto#11]
天猫检测进程 需要重新打包apk 换签名 变成彻底抹掉原来的记录 就行了

参考https://github.com/MonsterNone/tmall-miao

**Comment by czj2369** [comment]
> 天猫检测进程 需要重新打包apk 换签名 变成彻底抹掉原来的记录 就行了
> 
> 参考https://github.com/MonsterNone/tmall-miao

这个我有看过，我也试图去用另一种方式打包，现在进行到将js文件弄成了class文件和dex文件，但是不熟悉apk的打包方法，现在暂时没有头绪
