### ISSUE TITLE
进入组队页面就卡在那里了，我看代码里没有进入组队页面

### ISSUE THREAD

**Issue by king-zxw** [czj2369/jd_tb_auto#3]

**Comment by czj2369** [comment]
> _No description provided._

没做组队的部分，只做了日常任务的

**Comment by king-zxw** [comment]
组队页面没有任务，应该是这个选项在其他日常任务的前面，进去就不出来了

**Comment by czj2369** [comment]
> 组队页面没有任务，应该是这个选项在其他日常任务的前面，进去就不出来了

噢噢，那我加一层逻辑

**Comment by king-zxw** [comment]
我看到那个任务叫 所在战队成员满三人（0/1）（去完成）-_-

**Comment by king-zxw** [comment]
主页蛋糕那里右侧有个小精灵，连续点他有五个金币，可以写个点击的事件一直刷金币hhhh

**Comment by czj2369** [comment]
> 我看到那个任务叫 所在战队成员满三人（0/1）（去完成）-_-

因为我没加战队，所以没有存在这个任务，没办法涉及到这个逻辑，你手动把它完成了吧。。那个点金币的我试试看

**Comment by king-zxw** [comment]
我也没加战队，就是自己一个人的战队hhhh我什么时候能像你一样优秀

**Comment by czj2369** [comment]
> 我也没加战队，就是自己一个人的战队hhhh我什么时候能像你一样优秀

找到原因了，改了下，今天没得测试了，明天再搞了
