### ISSUE TITLE
jd加购物车活动

### ISSUE THREAD

**Issue by mhy-s** [czj2369/jd_tb_auto#38]
有些进入商品中，商品无货，没有加购物车按钮，导致加购物车执行失败。
![bedaa17869d5ef6ed23e0d243fdb77a](https://user-images.githubusercontent.com/62387869/139371948-695b1275-94a3-4025-ae93-1e42b0a12207.jpg)
停留在此不动了，

**Comment by MarsTLBAD** [comment]
好了，把第293行的5改成4就能成功添加购物车了，感谢大佬！

**Comment by kingxjs** [comment]
304行
```
//判断购物车图标 或者 浏览
if ((productList[index].parent() && productList[index].parent().child(5) && productList[index].parent().child(5).click()) || productList[index].click()) {
```
