### ISSUE TITLE
淘宝需要跳过小互动任务

### ISSUE THREAD

**Issue by code-world-Ming** [czj2369/jd_tb_auto#39]
![小互动任务](https://user-images.githubusercontent.com/21977942/139371071-c4f21961-5e24-41f8-80d5-4e439ea9c304.jpg)

**Comment by czj2369** [comment]
小互动部分能够自动完成，有部分完成不了，因为没有时间完善后续的部分。。可以在代码中修改下需要忽略的任务即可
