### ISSUE TITLE
没有如期进入全面叠蛋糕，进去了东东农场

### ISSUE THREAD

**Issue by ifconf** [czj2369/jd_tb_auto#4]
打开京东app之后，能够自动点“我的”，在下一步要进入“全民叠蛋糕”的时候进入了东东农场，试了几次都是这样。这个问题发生在红米4上面。

**Comment by 409915016** [comment]
这个还和京东版本有关系，有没有“我的”页面截图？

**Comment by czj2369** [comment]
如果遇到这种情况，可以直接打开叠蛋糕页面也可以的，我晚点把页面截图附上

**Comment by Lbosen** [comment]
版本是安卓最新，游戏互动那个 东东农场是第一个图标 叠蛋糕是第二个

> 这个还和京东版本有关系，有没有“我的”页面截图？
