### ISSUE TITLE
jd脚本时间间隔

### ISSUE THREAD

**Issue by Patrick20211992** [czj2369/jd_tb_auto#40]
大佬你好，我用完jd脚本经常在还没浏览完就因为超过30s自动返回，请问有更有效的解决办法嘛？（看过他人的帖子，没有效果）或者有无脚本文件可供下载，我想自己把时间修改延长下以完成任务，谢谢！（我是荣耀Magic2机型）

**Comment by Disky** [comment]
目录里面不就是源码吗？可以自行修改
