### ISSUE TITLE
京东是不是加强检测了

### ISSUE THREAD

**Issue by yws112358** [czj2369/jd_tb_auto#42]
从11.7开始，用脚本的时候，活动会提示：活动太火爆了。然后退掉脚本，自己手动点就没问题
如果手动操作之后执行脚本，可以使用一段时间，后边又开始。重新手动开始又可以了。看来得小心了，不知道咋检测的

**Comment by czj2369** [comment]
> 从11.7开始，用脚本的时候，活动会提示：活动太火爆了。然后退掉脚本，自己手动点就没问题 如果手动操作之后执行脚本，可以使用一段时间，后边又开始。重新手动开始又可以了。看来得小心了，不知道咋检测的

有点奇怪，我这几天都有在使用，暂时没出现这种情况，可以换个时间点执行脚本测试下

**Comment by MY36** [comment]
有的京东检测无障碍，无障碍关了不火爆

**Comment by yws112358** [comment]
> 有的京东检测无障碍，无障碍关了不火爆

确实，结束autox js （也就同时关闭了他的无障碍） 重新打开jd立马不火爆了  手动会吧

**Comment by saury** [comment]
火爆+1，而且我这里无解，关无障碍，关autojs，重启，ios上手动点一天都没用，安卓上一直火爆，而且连手动在安卓上都是火爆……
