### ISSUE TITLE
跑不动了

### ISSUE THREAD

**Issue by s1sunny** [czj2369/jd_tb_auto#47]
一直重复做第二行的任务，做完了也不进行下一个了。

**Comment by s1sunny** [comment]
把APP版本回退到10.3.3就可以了，10.3.4用不了。

**Comment by s1sunny** [comment]
手动进入任务界面运行脚本，可以做大部分任务。
但还是有一定的稳定性影响，需要盯着。有些任务会有小弹窗，导致无法正常返回任务界面。
那种浏览即完成的不会返回，只能等程序触发异常停留自动返回。
品牌墙也不正常。

感谢大佬的无私奉献。

**Comment by czj2369** [comment]
> 手动进入任务界面运行脚本，可以做大部分任务。 但还是有一定的稳定性影响，需要盯着。有些任务会有小弹窗，导致无法正常返回任务界面。 个别完成的不会返回，只能等程序触发异常停留自动返回。 品牌墙也不正常。
> 
> 感谢大佬的无私奉献。

这个版本没有去做修改。。就单纯从双十一版本进行简单的改造，所以可能会有一些不稳定，只能说解决半人工吧，不能全自动，我自己的话就是挂着，如果没有稳定跑完就重新开一遍0.0

**Comment by s1sunny** [comment]
> > 手动进入任务界面运行脚本，可以做大部分任务。 但还是有一定的稳定性影响，需要盯着。有些任务会有小弹窗，导致无法正常返回任务界面。 个别完成的不会返回，只能等程序触发异常停留自动返回。 品牌墙也不正常。
> > 感谢大佬的无私奉献。
> 
> 这个版本没有去做修改。。就单纯从双十一版本进行简单的改造，所以可能会有一些不稳定，只能说解决半人工吧，不能全自动，我自己的话就是挂着，如果没有稳定跑完就重新开一遍0.0

了解！那行吧，反正活动快结束了，目前半自动使用也很省事了，感谢您的付出与无私分享。
issuse close.
