### ISSUE TITLE
新的618脚本不能手动结束脚本

### ISSUE THREAD

**Issue by s1sunny** [czj2369/jd_tb_auto#50]
首先感谢大佬的付出，然后刚试用了脚本没办法正常用，APP版本最新的。
而且脚本也不能手动暂停，关掉autojs也一直在往左滑动。

**Comment by cucengineer** [comment]
当我开启定时启动后存在这个问题

**Comment by czj2369** [comment]
> 当我开启定时启动后存在这个问题

你代码里面设置了音量上键结束，你试试看

**Comment by czj2369** [comment]
> 首先感谢大佬的付出，然后刚试用了脚本没办法正常用，APP版本最新的。 而且脚本也不能手动暂停，关掉autojs也一直在往左滑动。

> 当我开启定时启动后存在这个问题

代码里面设置了音量上键结束，可以试试看
