### ISSUE TITLE
京东618脚本在浏览4个商品任务,加入购物车处报错

### ISSUE THREAD

**Issue by hardyio** [czj2369/jd_tb_auto#51]
![微信图片_20220530161822](https://user-images.githubusercontent.com/19840767/170949140-c21aa4d0-92b1-4e8a-80d6-7410935a0e2e.jpg)

**Comment by czj2369** [comment]
> ![微信图片_20220530161822](https://user-images.githubusercontent.com/19840767/170949140-c21aa4d0-92b1-4e8a-80d6-7410935a0e2e.jpg)

已修复部分错误
