### ISSUE TITLE
卡在 开启定时器

### ISSUE THREAD

**Issue by happyghw** [czj2369/jd_tb_auto#53]
auto.js 直接运行代码情况下，卡在 开启定时器。

**Comment by czj2369** [comment]
> auto.js 直接运行代码情况下，卡在 开启定时器。

检查下是否允许浮窗权限以及无障碍

**Comment by happyghw** [comment]
均已开启，apk 安装后同样。

**Comment by happyghw** [comment]
MI10S miui 13.0.5

**Comment by czj2369** [comment]
> MI10S miui 13.0.5

试下手动进入到这个页面呢？
![87d45e9e259d6b36762d7efcceb7707](https://user-images.githubusercontent.com/31198074/172059912-13a7905d-9a62-437b-902a-42954a723dda.jpg)

**Comment by czj2369** [comment]
> > MI10S miui 13.0.5
> 
> 试下手动进入到这个页面呢？活动界面 ![87d45e9e259d6b36762d7efcceb7707](https://user-images.githubusercontent.com/31198074/172060025-881e3c55-a814-4350-8fdf-01ae39cbc96f.jpg)

**Comment by happyghw** [comment]
手工进入活动界面后可以了，谢谢。
但是会卡在  下单返现金 这个任务 ，无法完成。

**Comment by czj2369** [comment]
> 手工进入活动界面后可以了，谢谢。 但是会卡在 下单返现金 这个任务 ，无法完成。

最新代码应该是有跳过这个任务的，我到时候再测测看
