### ISSUE TITLE
22年双11

### ISSUE THREAD

**Issue by WjInk052125** [czj2369/jd_tb_auto#55]
大佬今年双11还更新不

**Comment by joeyreg** [comment]
坐等大佬更新

**Comment by forpw2009** [comment]
大佬，今年又开始了~

**Comment by czj2369** [comment]
> 大佬，今年又开始了~

> 坐等大佬更新

> 大佬今年双11还更新不

已更新

**Comment by Whitecat-EX** [comment]
大佬，好像用不了

**Comment by CoderAWei** [comment]
好像没法成功运行哦。一直卡在``当前任务序号0``这里，手动打开任务列表也无法成功点击``去完成``

**Comment by czj2369** [comment]
> 大佬，好像用不了

描述一下情况

**Comment by czj2369** [comment]
> 好像没法成功运行哦。一直卡在`当前任务序号0`这里，手动打开任务列表也无法成功点击`去完成`

打开任务列表再运行任务试试，记得要把前面打开的脚本关闭，音量上键

**Comment by jjhjhx** [comment]
> > 好像没法成功运行哦。一直卡在`当前任务序号0`这里，手动打开任务列表也无法成功点击`去完成`
> 
> 打开任务列表再运行任务试试，记得要把前面打开的脚本关闭，音量上键

大佬，试过了这个方法，没有用，还是重复`当前任务序号0` 
本机安卓12

**Comment by czj2369** [comment]
> > > 好像没法成功运行哦。一直卡在`当前任务序号0`这里，手动打开任务列表也无法成功点击`去完成`
> > 
> > 
> > 打开任务列表再运行任务试试，记得要把前面打开的脚本关闭，音量上键
> 
> 大佬，试过了这个方法，没有用，还是重复`当前任务序号0` 本机安卓12

有可能是分辨率差别过大的原因导致，这一版是使用的坐标点击，一开始会设定分辨率为1090x1920
```console.log("当前任务序号：", TASK_ID)
    const button = text("去领取").exists() ? text("去领取").find()[0] : text("去完成").find()[TASK_ID];
    if (button != undefined) {
        const rect = button.bounds()
        const parentButton = button.parent();
        for (var i = 0; i < parentButton.childCount(); i++) {
            var b = parentButton.children()[i].bounds();
            if (rect.centerX() == b.centerX() && rect.centerY() == b.centerY()) {
                const info = parentButton.children()[i - 1];
                console.log("当前任务:", info.children()[1].text());
                if (info.children()[1].text().indexOf("浏览5个品牌墙店铺") >= 0) {
                    is_pp = true;
                }

            }
        }
        //sleep(2000);
        if (click(rect.centerX(), rect.centerY()) && click(rect.centerX(), rect.centerY())) {
            console.log("点击去完成");
            // 计时器重置
            JUDGE_TIME = 0;
            sleep(3000);
            return true;
        }
    }
```
因为无法完成去点击的步骤导致的，不过按道理走到这一步，在任务列表这里应该会执行才对
<img src="https://user-images.githubusercontent.com/31198074/197404334-9fffb46c-74e1-4c69-b2ea-09d4f91ce506.jpg" width="50%">

**Comment by Whitecat-EX** [comment]
就是悬浮窗一直显示任务0，完全做不了任务，刚下了1.0.1版本也是一样的问题

**Comment by Whitecat-EX** [comment]
> 就是悬浮窗一直显示任务0，完全做不了任务，刚下了1.0.1版本也是一样的问题

我是安卓11，小米9

**Comment by lijian66** [comment]
真系警告!

**Comment by jjhjhx** [comment]
> > > > 好像没法成功运行哦。一直卡在`当前任务序号0`这里，手动打开任务列表也无法成功点击`去完成`
> > > 
> > > 
> > > 打开任务列表再运行任务试试，记得要把前面打开的脚本关闭，音量上键
> > 
> > 
> > 大佬，试过了这个方法，没有用，还是重复`当前任务序号0` 本机安卓12
> 
> 有可能是分辨率差别过大的原因导致，这一版是使用的坐标点击，一开始会设定分辨率为1090x1920
> 
> ```
>     const button = text("去领取").exists() ? text("去领取").find()[0] : text("去完成").find()[TASK_ID];
>     if (button != undefined) {
>         const rect = button.bounds()
>         const parentButton = button.parent();
>         for (var i = 0; i < parentButton.childCount(); i++) {
>             var b = parentButton.children()[i].bounds();
>             if (rect.centerX() == b.centerX() && rect.centerY() == b.centerY()) {
>                 const info = parentButton.children()[i - 1];
>                 console.log("当前任务:", info.children()[1].text());
>                 if (info.children()[1].text().indexOf("浏览5个品牌墙店铺") >= 0) {
>                     is_pp = true;
>                 }
> 
>             }
>         }
>         //sleep(2000);
>         if (click(rect.centerX(), rect.centerY()) && click(rect.centerX(), rect.centerY())) {
>             console.log("点击去完成");
>             // 计时器重置
>             JUDGE_TIME = 0;
>             sleep(3000);
>             return true;
>         }
>     }
> ```
> 
> 因为无法完成去点击的步骤导致的，不过按道理走到这一步，在任务列表这里应该会执行才对 <img alt="" width="50%" src="https://user-images.githubusercontent.com/31198074/197404334-9fffb46c-74e1-4c69-b2ea-09d4f91ce506.jpg">

那需要自己调整坐标还是什么吗，怎么解决这个问题呢

**Comment by czj2369** [comment]
> 那需要自己调整坐标还是什么吗，怎么解决这个问题呢
你可以这一行代码下面加个日志打印，打印出
`const button = text("去领取").exists() ? text("去领取").find()[0] : text("去完成").find()[TASK_ID];`
这个button是不是能够获取到，我感觉是因为没办法获取到 ‘去完成’ 的坐标导致的

**Comment by czj2369** [comment]
> 就是悬浮窗一直显示任务0，完全做不了任务，刚下了1.0.1版本也是一样的问题，我是安卓11 小米9

你参考下我上面的任务列表图片的回复试试，或者自己会动源码的话，可以在这一行代码下面加个日志打印，打印出
`const button = text("去领取").exists() ? text("去领取").find()[0] : text("去完成").find()[TASK_ID];`
这个button是不是能够获取到，我感觉是因为没办法获取到 ‘去完成’ 的坐标导致的

**Comment by forpw2009** [comment]
亲，您的邮件我收到啦！
