### ISSUE TITLE
click rect isssue

### ISSUE THREAD

**Issue by inshyma** [czj2369/jd_tb_auto#58]
author 应该看下这个 [setScreenMetrics() 设置屏幕分辨率](https://github.com/hyb1996/Auto.js/issues/466)
我的手机分辨率1316x2560，完全用不了这个脚本。
click 都点错地方了

**Comment by czj2369** [comment]
> author 应该看下这个 [setScreenMetrics() 设置屏幕分辨率](https://github.com/hyb1996/Auto.js/issues/466) 我的手机分辨率1316x2560，完全用不了这个脚本。 click 都点错地方了
<img src="https://user-images.githubusercontent.com/31198074/198478797-ee79958e-4e3a-40e2-84af-3e577bcc36bd.jpg" width="50%">
我使用的是autoXjs，不知道这个版本作者有没有进行修复，但我在不同的分辨率两个手机测试是没问题的，你可以打开开发者选项的这两个功能， 看下实际的点击位置

**Comment by inshyma** [comment]
在我自己的设备上 点击位置明显点错了。但是我改了下方法
`/**
 * 根据坐标直接点击
 * @param {*} bounds 
 * @returns 
 */
function clickCenterXY(x1, y1, x2, y2) {
    // 计时器重置
    JUDGE_TIME = 0;
    setScreenMetrics(1090, 1920);
    let result = click((x1 + x2) / 2, (y1 + y2) / 2);
    setScreenMetrics(size[0], size[1]);
    return result;
}`

点击没有问题了
