### ISSUE TITLE
JD有问题

### ISSUE THREAD

**Issue by Lbosen** [czj2369/jd_tb_auto#6]
JD 去浏览大概5秒 就返回了 一直完不成

**Comment by czj2369** [comment]
> JD 去浏览大概5秒 就返回了 一直完不成

可能是一些判断被修改了，能具体说下是什么活动吗？

**Comment by Lbosen** [comment]
> ，能具体说下是什么活动吗？
用的你今天更新后的版本。
从开会员卡失败返回后，逛一逛的任务就出问题。
另外跳东东农场也是问题（安卓），首页有接口可以直接进

**Comment by czj2369** [comment]
> > ，能具体说下是什么活动吗？
> > 用的你今天更新后的版本。
> > 从开会员卡失败返回后，逛一逛的任务就出问题。
> > 另外跳东东农场也是问题（安卓），首页有接口可以直接进

好的，我的手机是没有跳到东东农场的，我试试修改下进入的接口，另外逛一逛的任务有时候是会出现逻辑错误导致无法运行，可以试试重开看看，我会试着修改这个问题

**Comment by czj2369** [comment]
> > ，能具体说下是什么活动吗？
> > 用的你今天更新后的版本。
> > 从开会员卡失败返回后，逛一逛的任务就出问题。
> > 另外跳东东农场也是问题（安卓），首页有接口可以直接进

朋友，我在首页那个接口是进不去的，我这边又没有问题，所以只能看下能不能将就下手动进入到活动界面。。= = （能力有限。。~）
