### ISSUE TITLE
JD 出错

### ISSUE THREAD

**Issue by joeyreg** [czj2369/jd_tb_auto#60]
1

**Comment by czj2369** [comment]
> 1

描述一下问题~

**Comment by xiaojieajie** [comment]
1. 任务1 浏览8秒的，还没做完就自动跳过去做下面的任务了。
2. 浏览4个商品和加购物车4件的任务无法正常工作

**Comment by czj2369** [comment]
> 1. 任务1 浏览8秒的，还没做完就自动跳过去做下面的任务了。
> 2. 浏览4个商品和加购物车4件的任务无法正常工作

我昨天测试了下，没有遇到类似的问题，我觉得可能是因为获取当前页面的控件有误造成的，这个我目前也没办法解决，可以尝试退出JD重启脚本，如果还存在这个问题，就是脚本本身的问题了
