### ISSUE TITLE
在任务列表的等待时间过长

### ISSUE THREAD

**Issue by DarkAge2018** [czj2369/jd_tb_auto#7]
完成任务后返回任务列表，到执行下一个任务，这期间的等待时间有8秒左右，是不是可以缩短一点呢

这个等待的时间和完成任务的时间差不多了，大大增加了完成全部任务的时间

希望可以优化一下

**Comment by czj2369** [comment]
> 完成任务后返回任务列表，到执行下一个任务，这期间的等待时间有8秒左右，是不是可以缩短一点呢
> 
> 这个等待的时间和完成任务的时间差不多了，大大增加了完成全部任务的时间
> 
> 希望可以优化一下

我试试看，因为是为了照顾一些老机，所以把等待时间设的有点长

**Comment by DarkAge2018** [comment]
> > 完成任务后返回任务列表，到执行下一个任务，这期间的等待时间有8秒左右，是不是可以缩短一点呢
> > 这个等待的时间和完成任务的时间差不多了，大大增加了完成全部任务的时间
> > 希望可以优化一下
> 
> 我试试看，因为是为了照顾一些老机，所以把等待时间设的有点长

京东优化比较好，实测3、4年前的骁龙625都可以流畅运行，改成两三秒就好了
淘宝就比较卡，可以设置比京东稍微长一点，但也不用像现在这么久

**Comment by czj2369** [comment]
> > > 完成任务后返回任务列表，到执行下一个任务，这期间的等待时间有8秒左右，是不是可以缩短一点呢
> > > 这个等待的时间和完成任务的时间差不多了，大大增加了完成全部任务的时间
> > > 希望可以优化一下
> > 
> > 
> > 我试试看，因为是为了照顾一些老机，所以把等待时间设的有点长
> 
> 京东优化比较好，实测3、4年前的骁龙625都可以流畅运行，改成两三秒就好了
> 淘宝就比较卡，可以设置比京东稍微长一点，但也不用像现在这么久

好的，我晚上回去改一下看看效果
