### ISSUE TITLE
大佬双十一来了，该更新了

### ISSUE THREAD

**Issue by 81pla** [czj2369/jd_tb_auto#8]
大佬双十一来了，该更新了
现在的版本淘宝打开一直在重复进入我的页面

**Comment by czj2369** [comment]
了解，我也才知道，晚上抽空改一下，上传个新版本，之前的大概是用不了了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;81pla&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月21日(星期三) 上午10:04
收件人:&nbsp;&quot;czj2369/jd_tb_auto&quot;<jd_tb_auto@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[czj2369/jd_tb_auto] 大佬双十一来了，该更新了 (#8)

**Comment by linux-nqh** [comment]
明天有最新版本可以用吗大佬

**Comment by czj2369** [comment]
> 明天有最新版本可以用吗大佬

已经更新了 不过没有打包 我稍后再打包一份

**Comment by linux-nqh** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "czj2369"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 晚上9:10
收件人: "czj2369/jd_tb_auto"<jd_tb_auto@noreply.github.com&gt;; 
抄送: "牛启豪"<1250007327@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [czj2369/jd_tb_auto] 大佬双十一来了，该更新了 (#8)





  
明天有最新版本可以用吗大佬
  
已经更新了 不过没有打包 我稍后再打包一份
